name: ixrev
services:
  microservice:
    container_name: microservice
    env_file:
      - src/config/environments/.env.development
    volumes:
      - .:/app # ? This will mount the current directory into the container. This allows for hot-reloading
    depends_on:
      - rdb
      - kafka

  rdb:
    container_name: rdb
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aleix
      POSTGRES_PASSWORD: Aleix2024
      POSTGRES_DB: ixrev

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

