name: ixrev
networks:
  ixrev-network:
    name: ixrev-network
    driver: bridge

services:
  microservice:
    container_name: microservice
    env_file:
      - src/config/environments/.env.production
    environment:
      - RDB_HOST=rdb
      - KAFKA_HOST=kafka
    networks:
      - ixrev-network
    depends_on:
      - rdb
      - kafka

  rdb:
    container_name: rdb
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aleix
      POSTGRES_PASSWORD: Aleix2024
      POSTGRES_DB: ixrev
    networks:
      - ixrev-network

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - ixrev-network

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092,PLAINTEXT_IP://
      # KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - ixrev-network
    depends_on:
      - zookeeper

